server:
  port: 8000
  servlet:
    context-path: /massage

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    time-zone=UTC
  datasource:
    username: massage
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/massage?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    port: 6379